

version: "3.9"

services:
  vault:
    container_name: vault-test
    
    image: hashicorp/vault

    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200

    ports:
      - 8100:8200

    volumes:
      - ./post_init:/post_init

    # command: |
    #   vault server -dev

