

version: "3.9"

services:
  vault:
    
    image: hashicorp/vault

    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200

    ports:
      - 8200:8200

    volumes:
      - ./fill_values.sh:/fill_values.sh

    # command: |
    #   vault server -dev

